In [1]:
import pandas as pd
from pandasql import sqldf

In [2]:
df1 = pd.read_csv("./SampleData.csv",encoding="ISO-8859-1")

/tmp/ipykernel_69623/1581311276.py:1: DtypeWarning: Columns (0: Website, 1: Date, 2: Next Follow Up, 3: ecode, 4: What attracted you to consider SomeSchool ) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("./SampleData.csv",encoding="ISO-8859-1")

In [3]:
df1.head()

,Prospect ID,Lead Number,Company,Lead Origin,Mobile Number,Website,Time Zone,Job Title,Lead Source,Source Medium,...,Stage Rotting Flag Level,Mailing Preferences,Twitter Id,Facebook Id,LinkedIn Id,Skype Id,Gtalk Id,Google Plus Id,Quality Score 01,Groups
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,NaN,API,NaN,NaN,NaN,NaN,Olark Chat,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,NaN,API,NaN,NaN,NaN,NaN,Organic Search,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,NaN,Landing Page Submission,NaN,NaN,NaN,NaN,Direct Traffic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,NaN,Landing Page Submission,NaN,NaN,NaN,NaN,Direct Traffic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3256f628-e534-4826-9d63-4a8b88782852,660681,NaN,Landing Page Submission,NaN,NaN,NaN,NaN,Google,CPC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df1.columns = df1.columns.str.replace(' ', '_')

In [5]:
df2 = pd.read_csv("./Leads.csv",encoding="ISO-8859-1")

In [6]:
df2.head()

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [7]:
df2.columns = df2.columns.str.replace(' ', '_')

In [8]:
df1.columns.to_list()

['Prospect_ID',
 'Lead_Number',
 'Company',
 'Lead_Origin',
 'Mobile_Number',
 'Website',
 'Time_Zone',
 'Job_Title',
 'Lead_Source',
 'Source_Medium',
 'Notes',
 'Source_Campaign',
 'Source_Content',
 'Do_Not_Email',
 'Do_Not_Call',
 'Lead_Stage',
 'Lead_Grade',
 'Lead_Score',
 'Order_Value',
 'Engagement_Score',
 'TotalVisits',
 'Page_Views_Per_Visit',
 'Average_Time_Per_Visit',
 'Last_Activity',
 'Last_Activity_Date',
 'Related_Landing_Page_Id',
 'First_Landing_Page_Submission_Id',
 'First_Landing_Page_Submission_Date',
 'Created_On',
 'Modified_On',
 'Lead_Conversion_Date',
 'Address_1',
 'Address_2',
 'Cityold',
 'State',
 'Country',
 'Zip',
 'Facebook_URL',
 'Twitter_URL',
 'LinkedIn_URL',
 'Industry',
 'Work_Area',
 'Course_Interested',
 'Keyword',
 'Date',
 'Specialization',
 'Entrance_Test',
 'How_did_you_hear_about_SomeSchool',
 'What_is_your_current_occupation',
 'If_you_are_a_working_professional',
 'If_you_are_a_working_professional_please_mention_',
 'What_matters_most_to_you_in_choosing_an_ADP',
 'Age',
 'Next_Follow_Up',
 'Search',
 'Magazine',
 'Newspaper_Article',
 'Welearn_Forums',
 'Newspaper',
 'Digital_Advertisement',
 'Through_Recommendations',
 'Any_other_Please_specify',
 'Last_Degree',
 'Receive_More_Updates_About_Our_Courses',
 'Admission_Number',
 'Tags',
 'Lead_Quality',
 'Update_me_on_Supply_Chain_Content',
 'Get_updates_on_PGDMHBSCM',
 'Chat_Group',
 'Lead_Profile',
 'City_New',
 'Country_New',
 'Industry_New',
 'Profile_Score',
 'Asymmetrique_Activity_Index',
 'Asymmetrique_Profile_Index',
 'ecode',
 'amt',
 'eventname',
 'Enquiry_Type',
 'Asymmetrique_Activity_Score',
 'Asymmetrique_Profile_Score',
 'Admission_Date',
 'I_agree_to_pay_the_amount_through_cheque',
 'Previous_Stage',
 'Number_of_Followup_Calls',
 'Asym_how_soon_you_can_join_program',
 'Asymm_Reason_to_take_admission',
 'Asymm_Are_you_aware_about_SomeSchool_College',
 'Asymm_Are_you_applying_for_any_other_form_of_MBA',
 'Asym_What_is_your_expectation_from_this_course',
 'Asym_How_do_you_feel_about_taking_admission',
 'Asym_What_stopping_you_from_joining_course',
 'Asym_What_are_your_concerns_for_taking_admission',
 'Asym_preferences_for_selecting_management_course',
 'a_free_copy_of_Mastering_The_Interview',
 'What_attracted_you_to_consider_SomeSchool_',
 'you_to_consider_SomeSchool_',
 'Landing_Page',
 'Admission_Constraints',
 'Lead_Type',
 'Asymmetrique_Scoring_Model',
 'Last_Notable_Activity',
 'Last_Notable_Activity_Date',
 'Source_Referrer',
 'Last_Visit_Date',
 'Photo_Url',
 'Stage_Rotting_Flag_Status',
 'Stage_Rotting_Flag_Message',
 'Stage_Rotting_Flag_Modification_Date',
 'Stage_Rotting_Flag_Additional_Info',
 'Stage_Rotting_Flag_Level',
 'Mailing_Preferences',
 'Twitter_Id',
 'Facebook_Id',
 'LinkedIn_Id',
 'Skype_Id',
 'Gtalk_Id',
 'Google_Plus_Id',
 'Quality_Score_01',
 'Groups']

In [9]:
df2.head()

,Prospect_ID,Lead_Number,Lead_Origin,Lead_Source,Do_Not_Email,Do_Not_Call,Converted,TotalVisits,Total_Time_Spent_on_Website,Page_Views_Per_Visit,...,Get_updates_on_DM_Content,Lead_Profile,City,Asymmetrique_Activity_Index,Asymmetrique_Profile_Index,Asymmetrique_Activity_Score,Asymmetrique_Profile_Score,I_agree_to_pay_the_amount_through_cheque,A_free_copy_of_Mastering_The_Interview,Last_Notable_Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [10]:
df2.columns.to_list()

['Prospect_ID',
 'Lead_Number',
 'Lead_Origin',
 'Lead_Source',
 'Do_Not_Email',
 'Do_Not_Call',
 'Converted',
 'TotalVisits',
 'Total_Time_Spent_on_Website',
 'Page_Views_Per_Visit',
 'Last_Activity',
 'Country',
 'Specialization',
 'How_did_you_hear_about_X_Education',
 'What_is_your_current_occupation',
 'What_matters_most_to_you_in_choosing_a_course',
 'Search',
 'Magazine',
 'Newspaper_Article',
 'X_Education_Forums',
 'Newspaper',
 'Digital_Advertisement',
 'Through_Recommendations',
 'Receive_More_Updates_About_Our_Courses',
 'Tags',
 'Lead_Quality',
 'Update_me_on_Supply_Chain_Content',
 'Get_updates_on_DM_Content',
 'Lead_Profile',
 'City',
 'Asymmetrique_Activity_Index',
 'Asymmetrique_Profile_Index',
 'Asymmetrique_Activity_Score',
 'Asymmetrique_Profile_Score',
 'I_agree_to_pay_the_amount_through_cheque',
 'A_free_copy_of_Mastering_The_Interview',
 'Last_Notable_Activity']

In [11]:
df1 = df1[df1['Lead_Origin'] == 'Landing Page Submission'].dropna(subset='Company')

In [12]:
df1.head()

,Prospect_ID,Lead_Number,Company,Lead_Origin,Mobile_Number,Website,Time_Zone,Job_Title,Lead_Source,Source_Medium,...,Stage_Rotting_Flag_Level,Mailing_Preferences,Twitter_Id,Facebook_Id,LinkedIn_Id,Skype_Id,Gtalk_Id,Google_Plus_Id,Quality_Score_01,Groups
18,82cb5fb0-2d97-4a39-a630-ab5fe2e7f18c,660522,Dr. Ram Manohar Lohia Avadh University /ugc,Landing Page Submission,NaN,NaN,NaN,NaN,Google,CPC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,cb28ce2a-61b5-4a41-aa99-b593c7d2ed81,659357,Yogeshsadarang@yahoo.in,Landing Page Submission,NaN,NaN,NaN,NaN,Google,CPC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,014b3eac-a050-4596-b0ad-0be984086a6c,657572,vinoba bhave university,Landing Page Submission,NaN,NaN,NaN,NaN,Referral Sites,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,549f44ca-7d3d-42ee-9868-cf00b86265af,655287,vkaradkar@in.imshealth.com,Landing Page Submission,NaN,NaN,NaN,NaN,Direct Traffic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,15c16425-0c3f-4edb-b266-b7bd312dca26,654061,rakshata.nikam@sharekhan.com,Landing Page Submission,NaN,NaN,NaN,NaN,Direct Traffic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df2.columns

Index(['Prospect_ID', 'Lead_Number', 'Lead_Origin', 'Lead_Source',
       'Do_Not_Email', 'Do_Not_Call', 'Converted', 'TotalVisits',
       'Total_Time_Spent_on_Website', 'Page_Views_Per_Visit', 'Last_Activity',
       'Country', 'Specialization', 'How_did_you_hear_about_X_Education',
       'What_is_your_current_occupation',
       'What_matters_most_to_you_in_choosing_a_course', 'Search', 'Magazine',
       'Newspaper_Article', 'X_Education_Forums', 'Newspaper',
       'Digital_Advertisement', 'Through_Recommendations',
       'Receive_More_Updates_About_Our_Courses', 'Tags', 'Lead_Quality',
       'Update_me_on_Supply_Chain_Content', 'Get_updates_on_DM_Content',
       'Lead_Profile', 'City', 'Asymmetrique_Activity_Index',
       'Asymmetrique_Profile_Index', 'Asymmetrique_Activity_Score',
       'Asymmetrique_Profile_Score',
       'I_agree_to_pay_the_amount_through_cheque',
       'A_free_copy_of_Mastering_The_Interview', 'Last_Notable_Activity'],
      dtype='str')

In [14]:
df2 = df2[df2['Lead_Origin'] == 'Landing Page Submission']

In [15]:
df2.head()

,Prospect_ID,Lead_Number,Lead_Origin,Lead_Source,Do_Not_Email,Do_Not_Call,Converted,TotalVisits,Total_Time_Spent_on_Website,Page_Views_Per_Visit,...,Get_updates_on_DM_Content,Lead_Profile,City,Asymmetrique_Activity_Index,Asymmetrique_Profile_Index,Asymmetrique_Activity_Score,Asymmetrique_Profile_Score,I_agree_to_pay_the_amount_through_cheque,A_free_copy_of_Mastering_The_Interview,Last_Notable_Activity
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
6,9fae7df4-169d-489b-afe4-0f3d752542ed,660673,Landing Page Submission,Google,No,No,1,2.0,1640,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,No,Modified
8,cfa0128c-a0da-4656-9d47-0aa4e67bf690,660624,Landing Page Submission,Direct Traffic,No,No,0,2.0,71,2.0,...,No,NaN,Thane & Outskirts,02.Medium,02.Medium,14.0,14.0,No,Yes,Email Opened

In [16]:
merged_df = pd.merge(df1,df2,on="Lead_Number",how='outer', suffixes=("_left","_right"))

In [17]:
merged_df.columns

Index(['Prospect_ID_left', 'Lead_Number', 'Company', 'Lead_Origin_left',
       'Mobile_Number', 'Website', 'Time_Zone', 'Job_Title',
       'Lead_Source_left', 'Source_Medium',
       ...
       'Get_updates_on_DM_Content', 'Lead_Profile_right', 'City',
       'Asymmetrique_Activity_Index_right', 'Asymmetrique_Profile_Index_right',
       'Asymmetrique_Activity_Score_right', 'Asymmetrique_Profile_Score_right',
       'I_agree_to_pay_the_amount_through_cheque_right',
       'A_free_copy_of_Mastering_The_Interview',
       'Last_Notable_Activity_right'],
      dtype='str', length=158)

In [18]:
filtered_df = merged_df[merged_df['Lead_Origin'] == 'Landing Page Submission'].dropna(subset="Company")

KeyError: 'Lead_Origin'

In [ ]:
# common_columns = set(df1.columns).intersection(
#                 set(df2.columns))
# common_columns

In [ ]:
merged_df.columns.to_list()

In [ ]:
merged_df['Mobile_Number'].unique()

In [ ]:
merged_df['Company'].unique()

In [ ]:
# query = """
# SELECT *
# FROM df1 c
# JOIN df2 o
# ON c.Prospect_ID = o.Prospect_ID
# """

# result = sqldf(query)
# result

In [ ]:
# result['City']

In [ ]:
import pandas as pd
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s"
)
logger = logging.getLogger(__name__)


class DataProcessor:
    """
    A class to handle merging, filtering, and cleaning of two CSV datasets based on lead information.
    """

    def __init__(self, df1_path: str, df2_path: str):
        """
        Initializes the DataProcessor by loading two CSV files into DataFrames.
        """
        try:
            self.df1 = pd.read_csv(df1_path)
            logger.info(f"✅ Loaded first CSV: {df1_path} | Shape: {self.df1.shape}")

            self.df2 = pd.read_csv(df2_path, encoding="ISO-8859-1")
            logger.info(f"✅ Loaded second CSV: {df2_path} | Shape: {self.df2.shape}")

        except FileNotFoundError as e:
            logger.error(f"❌ File not found: {e}")
            raise
        except pd.errors.ParserError as e:
            logger.error(f"❌ Error parsing CSV: {e}")
            raise
        except Exception as e:
            logger.error(f"❌ Unexpected error during initialization: {e}")
            raise

    def _merge_dataframes(self, merge_on_column: str) -> pd.DataFrame:
        """
        Merges two DataFrames on a specified column, avoiding duplication on common columns.
        """
        try:
            common_columns = set(self.df1.columns).intersection(set(self.df2.columns))
            common_columns.remove(merge_on_column)
            logger.debug(f"Common columns (excluding key): {common_columns}")

            merged_df = pd.merge(
                self.df1,
                self.df2.drop(columns=list(common_columns)),
                on=merge_on_column,
                how="outer"
            )

            logger.info(
                f"🔗 Merged DataFrames on '{merge_on_column}' | Shape before: "
                f"{self.df1.shape}, {self.df2.shape} | After merge: {merged_df.shape}"
            )

            return merged_df
        except KeyError as e:
            logger.error(f"❌ Column not found for merging: {e}")
            raise
        except Exception as e:
            logger.error(f"❌ Error while merging DataFrames: {e}")
            raise

    def _drop_columns_with_missing_threshold(
        self, df: pd.DataFrame, threshold: float = 0.6
    ) -> pd.DataFrame:
        """
        Drops columns if missing/empty/null values exceed a given threshold.
        """
        try:
            logger.info(f"🧹 Checking for columns with missing ratio > {threshold:.2f}")

            # Calculate missing ratios
            missing_ratio = df.isnull().mean()
            empty_ratio = (df.astype(str).apply(lambda x: x.str.strip() == "").mean())
            total_missing_ratio = (missing_ratio + empty_ratio) / 2

            cols_to_drop = total_missing_ratio[total_missing_ratio > threshold].index
            logger.debug(f"Missing ratio per column:\n{total_missing_ratio}")

            if len(cols_to_drop) > 0:
                logger.info(
                    f"🚮 Dropping {len(cols_to_drop)} columns exceeding {threshold*100:.0f}% missing threshold."
                )
                logger.debug(f"Columns dropped: {list(cols_to_drop)}")

            cleaned_df = df.drop(columns=cols_to_drop)
            logger.info(f"✅ Shape after dropping columns: {cleaned_df.shape}")

            return cleaned_df
        except Exception as e:
            logger.error(f"❌ Error while dropping columns: {e}")
            raise

    def get_filter_data(self, threshold: float = 0.6) -> pd.DataFrame:
        """
        Merges, filters, and cleans the DataFrame to include only relevant leads and remove
        columns with excessive missing values.
        """
        try:
            merged_df = self._merge_dataframes(merge_on_column="Lead Number")

            logger.info(
                f"📊 Starting filter operation | Shape before filtering: {merged_df.shape}"
            )

            # Filter rows
            filtered_df = merged_df[merged_df["Lead Origin"] == "Landing Page Submission"]
            filtered_df = filtered_df.dropna(subset=["Company"])

            logger.info(
                f"✨ Filtered DataFrame | Rows before: {merged_df.shape[0]}, after filtering: {filtered_df.shape[0]}"
            )

            # Drop columns with high missing ratio
            cleaned_df = self._drop_columns_with_missing_threshold(filtered_df, threshold)

            logger.info(
                f"🏁 Final cleaned DataFrame | Shape: {cleaned_df.shape} | Columns retained: {len(cleaned_df.columns)}"
            )
            return cleaned_df

        except KeyError as e:
            logger.error(f"❌ Required column missing during filtering: {e}")
            raise
        except Exception as e:
            logger.error(f"❌ Error during data filtering: {e}")
            raise

    def save_filtered_dataframe(
        self, filtered_dataframe: pd.DataFrame, path: str, index: bool = False
    ) -> str:
        """
        Saves a DataFrame to a CSV file.
        """
        try:
            filtered_dataframe.to_csv(path, index=index)
            logger.info(
                f"💾 DataFrame successfully saved | Path: {path} | Shape: {filtered_dataframe.shape}"
            )
            return f"DataFrame successfully saved to {path}"
        except Exception as e:
            logger.error(f"❌ Failed to save DataFrame: {e}")
            raise

In [ ]:
processor = DataProcessor()

In [ ]:
merged_df_1 = processor.get_merged_data(df1=df1,df2=df2,filters_merged={'lead_origin':'Landing Page Submission'},non_null_cols_merged=['Company'], on='lead_number')

In [ ]:
merged_df_1

In [ ]:
df1_mod = processor.modify_columns(df=df1)
df2_mod = processor.modify_columns(df=df2)

In [ ]:
df1_mod_fil = processor.filter_df(filters={})